"""
Generates topics.json with 500 pre-seeded CipherPulse video topics.
Run once during project setup: python generate_topics.py
"""
import json
from pathlib import Path

# fmt: off
RAW_TOPICS: list[tuple[str, int]] = [
    # ── INCIDENT BREAKDOWNS (format 1) ────────────────────────────────────────
    ("The Equifax Breach: 147 Million Americans Exposed in 2017", 1),
    ("SolarWinds Supply Chain Attack: How Russia Hacked the US Government", 1),
    ("Colonial Pipeline Ransomware: How Hackers Shut Down US Fuel Supply", 1),
    ("WannaCry: The Ransomware That Infected 200,000 Computers in 150 Countries", 1),
    ("Stuxnet: The World's First Cyberweapon That Destroyed Physical Machines", 1),
    ("The Yahoo Breach: 3 Billion Accounts Stolen and Hidden for Years", 1),
    ("Target 2013: How Hackers Stole 40 Million Credit Cards Through an HVAC Vendor", 1),
    ("MOVEit: The Zero-Day That Hit 2,500 Organizations in Weeks", 1),
    ("LastPass Breach: Your Encrypted Password Vault Was Stolen", 1),
    ("The Twitter Bitcoin Scam: How 17-Year-Olds Hacked Obama, Biden, and Musk", 1),
    ("Marriott Breach: 500 Million Guest Records Exposed for 4 Years Undetected", 1),
    ("The JPMorgan Hack: How Hackers Stole 76 Million Customer Records", 1),
    ("NotPetya: The $10 Billion Cyberattack Disguised as Ransomware", 1),
    ("Uber's Cover-Up: Paying Hackers $100K to Delete Stolen Data and Stay Quiet", 1),
    ("The Sony Pictures Hack: North Korea's Hollywood Takedown", 1),
    ("T-Mobile's Fifth Breach in 5 Years: Chronic Negligence or Systemic Failure?", 1),
    ("Change Healthcare Attack: Why One Hack Broke US Medical Payments", 1),
    ("MGM Resorts: Hackers Used a 10-Minute Phone Call to Take Down $100M in Systems", 1),
    ("Caesars Entertainment: Paid $15M Ransom While MGM Refused", 1),
    ("The Home Depot Breach: 56 Million Cards Stolen via Contractor Credentials", 1),
    ("NSA's Shadow Brokers: When the Most Powerful Hacking Tools Were Leaked Online", 1),
    ("Operation Aurora: China Hacked Google, Adobe, and 30 Other Tech Companies", 1),
    ("Ashley Madison Hack: 37 Million Cheaters Exposed and the Suicides That Followed", 1),
    ("The Bangladesh Bank Heist: $81M Stolen via SWIFT Banking System", 1),
    ("Kaseya VSA: One Hack That Infected 1,500 Businesses Through IT Software", 1),
    ("REvil Ransomware Gang: How the FBI Secretly Infiltrated Them", 1),
    ("The OPM Breach: China Stole Personnel Files of 22 Million US Federal Employees", 1),
    ("Adobe 2013: 153 Million User Records — and the Passwords Were Encrypted Wrong", 1),
    ("LinkedIn 2012: 117 Million Passwords Cracked and Sold 4 Years Later", 1),
    ("The PlayStation Network Breach: 77 Million Accounts and 23 Days of Downtime", 1),
    ("Heartbleed: The SSL Bug That Left Half the Internet Vulnerable for 2 Years", 1),
    ("Shellshock: The 25-Year-Old Bash Bug That Gave Attackers Full Control", 1),
    ("Log4Shell: One Line of Java Code That Broke the Internet in 2021", 1),
    ("The Twitch Leak: All Source Code, Streamer Earnings, and Internal Data Exposed", 1),
    ("GoDaddy's Triple Breach: Same Company, Same Attacker, Three Separate Times", 1),
    ("The Capital One Breach: Ex-AWS Engineer Exploited SSRF to Steal 100M Records", 1),
    ("Verkada Camera Hack: 150,000 Security Cameras at Tesla, Jails, Hospitals Exposed", 1),
    ("The SIM Swap Epidemic: How Criminals Steal Your Phone Number to Drain Accounts", 1),
    ("Lazarus Group: North Korea's State-Sponsored Hacking Team That Funds the Regime", 1),
    ("Anonymous vs. HBGary Federal: The Day Hacktivists Destroyed a Security Firm", 1),
    ("The iCloud Celebgate: How 'The Fappening' Exploited Weak Apple Security", 1),
    ("Mt. Gox: The $450M Bitcoin Exchange Collapse That Almost Killed Crypto", 1),
    ("Poly Network DeFi Hack: $611M Stolen — Then the Hacker Returned It All", 1),
    ("The Ronin Bridge Hack: North Korea Stole $625M in Crypto in One Transaction", 1),
    ("Wormable BlueKeep: Microsoft's Nightmare Vulnerability Affecting All Old Windows", 1),
    ("The 2020 US Election Infrastructure Attacks: What Really Happened", 1),
    ("JBS Meatpacking Ransomware: How Hackers Disrupted the US Food Supply", 1),
    ("CNA Financial: $40M Ransom Paid to Ransomware Gang — Largest Known Payment", 1),
    ("The SolarWinds Hack Timeline: 9 Months Undetected in 18,000 Networks", 1),
    ("Lapsus$: The Teenage Hacking Gang That Breached Microsoft, Nvidia, and Samsung", 1),
    ("How Hackers Took Down Dyn DNS and Killed Twitter, Netflix, and Reddit for a Day", 1),
    ("The Water Treatment Plant Hack: Hacker Tried to Poison Oldsmar, Florida's Water", 1),
    ("Hafnium: China Exploited Microsoft Exchange to Hack 250,000 Servers in 30 Days", 1),
    ("The Medibank Breach: Australia's Largest Health Insurer Exposed 9.7M Patient Records", 1),
    ("Reddit Phishing Attack 2023: Two-Factor Wasn't Enough", 1),
    ("The Okta Breach: A Support Ticket Gave Hackers Access to 134 Customer Environments", 1),
    ("ALPHV BlackCat Ransomware: The FBI Disrupted Them — Then They Came Back", 1),
    ("Cl0p Ransomware: How One Gang Exploited GoAnywhere, MOVEit, and More in One Year", 1),
    ("The Air India Breach: 4.5 Million Passenger Records Including Passport Data Stolen", 1),
    ("Robinhood 2021: 5 Million Emails Stolen via Customer Support Social Engineering", 1),
    ("The Worm That Ate Iran: Stuxnet's Full Story from Discovery to Attribution", 1),
    ("Hackers Shut Down a US Hospital — and a Patient Died", 1),
    ("The Code Spaces Attack: Hackers Deleted Everything and a Company Ceased to Exist", 1),
    ("2014 Snapchat Leak: 4.6 Million Usernames and Phone Numbers — by Security Researchers", 1),
    ("How The Mirai Botnet Was Built by Three College Students for Minecraft", 1),
    ("Pegasus Spyware: How NSO Group Hacked Activists, Journalists, and World Leaders", 1),
    ("The Ticketmaster Breach 2024: ShinyHunters Stole 560 Million Customer Records", 1),
    ("AT&T Data Breach 2024: Call and Text Records of Nearly All Customers Exposed", 1),
    ("The Delta Air Lines Hack: CrowdStrike Update Caused the Largest IT Outage in History", 1),
    ("Salt Typhoon: China's Hackers Inside US Telecom Networks for Over a Year", 1),
    ("The PowerSchool Breach: 62 Million Student Records Stolen from a Single Platform", 1),

    # ── AI REVEALS (format 2) ─────────────────────────────────────────────────
    ("This AI Can Clone Your Voice From a 3-Second Clip", 2),
    ("GPT-4 Can Write Malware Better Than Most Hackers", 2),
    ("This AI Deepfake Tool Costs $0 and Runs on Your Laptop", 2),
    ("AI-Powered Phishing Emails Are Now Indistinguishable From Real Ones", 2),
    ("This AI Can Guess Your Password by Listening to You Type", 2),
    ("Meta's AI Can Read Your Brainwaves and Reconstruct What You're Hearing", 2),
    ("AI Can Now Detect Lies Better Than Humans — Here's What That Means", 2),
    ("This AI Generates Realistic Fake IDs That Pass Document Verification", 2),
    ("Google's AI Can Predict Where You'll Be Tomorrow Based on Your Data", 2),
    ("AI-Generated Faces Are Now More 'Human' Than Real Photos", 2),
    ("This AI Can Crack Any CAPTCHA in Under 1 Second", 2),
    ("OpenAI's o1 Attempted to Prevent Itself from Being Shut Down", 2),
    ("AI Worms Can Now Spread Between AI Agents Without Human Interaction", 2),
    ("This AI Can Reconstruct Text You Deleted From Screen Reflections", 2),
    ("China's AI Can Identify You in a Crowd Even When You're Masked", 2),
    ("AI Is Now Writing Zero-Day Exploits — And Selling Them", 2),
    ("This AI Reads Emotions in Real Time — and Governments Are Buying It", 2),
    ("Deepfake CEO Video Calls Are Being Used to Steal Millions From Companies", 2),
    ("AI Can Now Jailbreak Itself Without Human Prompting", 2),
    ("This AI Predicts Your Health Conditions From a 30-Second Voice Sample", 2),
    ("Google DeepMind's AI Discovered New Cyberattack Techniques on Its Own", 2),
    ("AI-Generated Synthetic Identities Are Opening Real Bank Accounts", 2),
    ("This AI Can Social Engineer Humans Better Than Trained Con Artists", 2),
    ("The AI That Can Identify You From Your Typing Rhythm Alone", 2),
    ("Autonomous AI Agents Are Completing Cyberattacks End-to-End Without Humans", 2),
    ("This AI Tool Can Generate a Convincing Phishing Site in Under 30 Seconds", 2),
    ("AI Is Now Being Used to Automate Business Email Compromise at Scale", 2),
    ("An AI System Discovered a Major Vulnerability in Linux — Before Any Human Did", 2),
    ("This AI Can Generate Working Exploits From CVE Descriptions Alone", 2),
    ("ChatGPT Can Be Tricked Into Providing Dangerous Information 97% of the Time", 2),
    ("AI-Generated OSINT: Bots Can Now Build a Full Profile on You in Minutes", 2),
    ("This AI Detects Hidden Malware Invisible to Traditional Antivirus", 2),
    ("Anthropic's Research Shows Claude Will Lie to Preserve Itself", 2),
    ("AI Is Automating the Job of Penetration Testers — and It's Better at It", 2),
    ("This AI Tool Can Impersonate Any Person's Writing Style Perfectly", 2),

    # ── MYTH BUSTERS (format 3) ───────────────────────────────────────────────
    ("You Think VPNs Make You Anonymous Online? Here's the Truth", 3),
    ("You Think Strong Passwords Keep You Safe? Password Managers Can Be Hacked Too", 3),
    ("You Think Private Browsing Hides Your Activity? It Doesn't Do What You Think", 3),
    ("You Think Antivirus Software Stops Hackers? Modern Attackers Bypass It Easily", 3),
    ("You Think Only Windows Gets Viruses? Macs Get Hacked More Than You Know", 3),
    ("You Think 2FA Is Unbreakable? SIM Swapping and SS7 Attacks Bypass It Instantly", 3),
    ("You Think Hackers Only Target Big Companies? Small Businesses Are Easier Prey", 3),
    ("You Think Deleting Files Removes Them? Here's What Actually Happens", 3),
    ("You Think Your Smart TV Isn't Spying on You? Think Again", 3),
    ("You Think HTTPS Means a Website Is Safe? That's a Dangerous Myth", 3),
    ("You Think Turning Off Location Stops Google Tracking You? Wrong", 3),
    ("You Think Airplane Mode Makes Your Phone Untraceable? Not Quite", 3),
    ("You Think Encryption Protects Your iCloud Backup? Apple Has the Key", 3),
    ("You Think Public WiFi Is Safe If You Use HTTPS? Here's the Full Story", 3),
    ("You Think AI-Generated Content Is Easy to Detect? Detection Tools Are Failing", 3),
    ("You Think Your Password Was Never Leaked? Check HaveIBeenPwned First", 3),
    ("You Think Cybercriminals Are Sophisticated Geniuses? Most Attacks Are Embarrassingly Simple", 3),
    ("You Think the Dark Web Is Only for Criminals? Here's What's Really There", 3),
    ("You Think Biometric Auth Is More Secure Than Passwords? Not Always", 3),
    ("You Think Covering Your Webcam Is Paranoid? Here's Why Zuckerberg Does It", 3),

    # ── HOW IT WORKS (format 4) ───────────────────────────────────────────────
    ("How Phishing Attacks Actually Work — In 60 Seconds", 4),
    ("How Ransomware Encrypts Your Files and Holds Them Hostage", 4),
    ("How Deepfakes Are Made: The Technology Behind AI Face Swaps", 4),
    ("How Password Cracking Works: Dictionary, Brute Force, and Rainbow Tables", 4),
    ("How a Man-in-the-Middle Attack Intercepts Your Data", 4),
    ("How SQL Injection Can Dump an Entire Database in Seconds", 4),
    ("How Social Engineering Bypasses Every Technical Security Control", 4),
    ("How a Zero-Day Exploit Is Discovered, Sold, and Weaponized", 4),
    ("How Keyloggers Record Every Keystroke Without You Knowing", 4),
    ("How Botnets Are Built From Millions of Hacked Devices", 4),
    ("How the Dark Web Actually Works — Tor, Onion Routing Explained Simply", 4),
    ("How Stalkerware Secretly Monitors Your Phone Without Detection", 4),
    ("How DNS Hijacking Redirects You to Fake Websites That Look Real", 4),
    ("How Supply Chain Attacks Compromise Software Before You Download It", 4),
    ("How Credential Stuffing Uses One Leaked Password to Break Into 50 Accounts", 4),
    ("How OSINT Lets Anyone Build a Full Profile on You Using Public Data", 4),
    ("How Evil Twin WiFi Attacks Steal Your Data at Airports and Cafes", 4),
    ("How Juice Jacking Uses Public USB Charging Ports to Hack Your Phone", 4),
    ("How Quantum Computing Will Break Every Encryption Standard We Use Today", 4),
    ("How Browser Fingerprinting Tracks You Without Cookies or Login", 4),
    ("How Formjacking Silently Steals Credit Cards From Legitimate Websites", 4),
    ("How Vishing (Voice Phishing) Scams Steal Banking Credentials by Phone", 4),
    ("How AI Voice Cloning Is Used to Authorize Fraudulent Wire Transfers", 4),
    ("How the SS7 Protocol Flaw Lets Anyone Track Your Phone's Location", 4),
    ("How a Rubber Ducky USB Drive Can Hack Any Computer in 30 Seconds", 4),
    ("How Facial Recognition Works — And Why It Gets It Wrong", 4),
    ("How Cryptocurrency Mixers Launder Billions in Stolen Crypto", 4),
    ("How Insider Threats Are Statistically More Dangerous Than External Attacks", 4),
    ("How AI Models Are Poisoned to Produce Wrong — or Dangerous — Outputs", 4),
    ("How Prompt Injection Attacks Hijack AI Assistants", 4),
    ("How Data Brokers Collect and Sell Your Personal Information Legally", 4),
    ("How End-to-End Encryption Actually Works — And Its Real Limits", 4),
    ("How Steganography Hides Secret Messages Inside Innocent Images", 4),
    ("How a Watering Hole Attack Targets an Entire Industry Through One Website", 4),
    ("How Adversarial AI Images Fool Computer Vision With Invisible Edits", 4),

    # ── LIST / RANKINGS (format 5) ────────────────────────────────────────────
    ("5 Signs Your Phone Has Been Hacked Right Now", 5),
    ("7 Things Hackers Know About You From Your Social Media", 5),
    ("The 5 Most Dangerous Hacking Groups in the World Right Now", 5),
    ("6 Free Tools That Protect Your Privacy Better Than Any VPN", 5),
    ("4 Types of Malware You've Probably Already Encountered", 5),
    ("The Top 10 Worst Data Breaches in History — Ranked by Damage", 5),
    ("5 Browser Extensions That Are Actually Spying on You", 5),
    ("3 Mistakes That Make You the Perfect Phishing Target", 5),
    ("The 7 Biggest AI Safety Failures So Far", 5),
    ("5 Countries With the Most Advanced Cyber Warfare Programs", 5),
    ("8 Signs a Website Is Fake Before You Even Log In", 5),
    ("The 4 Most Common Ways People Get Their Accounts Hacked", 5),
    ("5 Cybersecurity Myths That Are Getting People Hacked", 5),
    ("6 Privacy Settings You Should Change on Your iPhone Right Now", 5),
    ("6 Privacy Settings You Should Change on Your Android Right Now", 5),
    ("The 5 Most Dangerous Apps Still on the App Store", 5),
    ("3 Things Hackers Do in the First 60 Minutes After Breaking Into a Network", 5),
    ("7 Real Tools Hackers Use That You Can Download for Free", 5),
    ("4 Reasons Why Small Businesses Are Hackers' Favorite Targets", 5),
    ("The 5 Biggest AI Deepfake Scams of the Past Year", 5),
    ("6 Cybersecurity Careers That Pay Over $150K — No Degree Required", 5),
    ("5 Dark Web Marketplaces That Were Taken Down by Law Enforcement", 5),
    ("The 4 Types of Hackers — Which One Should You Actually Fear?", 5),
    ("5 VPNs That Were Caught Selling Your Data", 5),
    ("8 Items in Your Home That Are Actively Spying on You", 5),
    ("The 3 Biggest AI Risks According to the World's Top Scientists", 5),
    ("5 Ways Your Employer Can Legally Monitor You Right Now", 5),
    ("4 Tactics Scammers Use Specifically on the Elderly", 5),
    ("The 6 Most Notorious Hackers in History — and What Happened to Them", 5),
    ("5 Critical Infrastructure Systems That Have Already Been Hacked", 5),
    ("7 Red Flags in a Text Message That Mean You're Being Scammed", 5),
    ("The 4 Phases of a Professional Cyberattack — Step by Step", 5),
    ("5 AI Tools That Could Be Misused for Surveillance Right Now", 5),
    ("6 Things the NSA Can Do That Still Aren't Public Knowledge", 5),
    ("The 3 Biggest Mistakes Companies Make After a Data Breach", 5),

    # ── NEWS REACT (format 6) — headlines to be fetched live via news_fetcher ─
    ("LIVE: Breaking Cybersecurity Story — News React", 6),
    ("LIVE: Latest AI Development — News React", 6),
    ("LIVE: New Ransomware Campaign Targeting Critical Infrastructure", 6),
    ("LIVE: Zero-Day Vulnerability Disclosed — News React", 6),
    ("LIVE: Major Data Breach Announced — News React", 6),
    ("LIVE: Government Cybersecurity Advisory — News React", 6),
    ("LIVE: New AI Model Release and Security Implications", 6),
    ("LIVE: Nation-State Cyberattack Breaking News", 6),
    ("LIVE: Big Tech Privacy Scandal — News React", 6),
    ("LIVE: Ransomware Group Takedown — News React", 6),

    # ── PRIVACY & SURVEILLANCE (format 4 & 5 mix) ────────────────────────────
    ("How Facebook Tracks You Even When You're Not on Facebook", 4),
    ("How Google Knows Where You Slept Last Night", 4),
    ("How Your Car Is Secretly Building a Data Profile on You", 4),
    ("How Advertisers Build a Shadow Profile Before You Sign Up", 4),
    ("How Law Enforcement Uses Geofence Warrants to Track Everyone at a Location", 4),
    ("How Facial Recognition Has Wrongly Arrested 5 Innocent People So Far", 4),
    ("The Data Your Phone Sends to Apple and Google Every 4.5 Minutes", 5),
    ("5 Things Your ISP Knows About You and Can Legally Sell", 5),
    ("How License Plate Readers Are Building a National Movement Database", 4),
    ("The Hidden Danger of Sharing Your Location in Dating Apps", 4),
    ("How Smart Speakers Record Conversations Without Their Wake Word", 4),
    ("The Privacy Nightmare Inside Your Fitness Tracker's Data Policy", 4),
    ("How Retail Stores Track Your Shopping Behavior Using Bluetooth", 4),
    ("How TikTok Collects Data That No Other App Dares to Ask For", 4),
    ("Why Privacy-First Search Engines Still Leak Your Data", 3),
    ("How Your Deleted WhatsApp Messages Aren't Really Gone", 4),
    ("The Hidden Risk in Sharing Your DNA With Ancestry Sites", 4),
    ("How Stalkers Are Using AirTags to Track Victims in Plain Sight", 4),
    ("Why Signal Is the Only Messenger That Can't Reveal Your Data", 4),
    ("How Zero-Knowledge Proof Lets You Prove You Know Something Without Revealing It", 4),

    # ── PRACTICAL SECURITY TIPS (format 5 & 3 mix) ───────────────────────────
    ("How to Check If Your Email Was Leaked in a Data Breach Right Now", 4),
    ("The Only Password Strategy That Actually Keeps You Safe in 2025", 5),
    ("How to Set Up 2FA the Right Way — Not All 2FA Is Equal", 4),
    ("Why You Should Never Use SMS for Two-Factor Authentication", 3),
    ("How to Make Your Gmail Completely Impossible to Breach", 5),
    ("The Right Way to Use a VPN — And When Not to Bother", 5),
    ("How to Detect if Stalkerware Is on Your Phone in Under 5 Minutes", 4),
    ("5 Things to Do Immediately If You Think You've Been Hacked", 5),
    ("Why You Need to Freeze Your Credit Right Now — Even If You're Young", 3),
    ("How to Create a Digital Will Before Your Accounts Are Inaccessible Forever", 4),
    ("The Browser Settings That Stop 90% of Online Tracking Immediately", 5),
    ("How to Spot a Fake Login Page Before You Enter Your Password", 4),
    ("Why Reusing Passwords Is the Most Dangerous Thing You Do Online", 3),
    ("How to Secure Your Home WiFi Router in 10 Minutes", 5),
    ("The Right Way to Dispose of Old Devices So Your Data Is Gone Forever", 4),
    ("How to Know If Your Webcam Has Been Accessed Without Permission", 4),
    ("5 Security Mistakes Even Tech-Savvy People Make", 5),
    ("Why Updating Software Immediately Is Your Best Defense Against Hackers", 3),
    ("How to Lock Down Your Social Media Before Hackers Use It Against You", 5),
    ("The One Setting That Stops Most Ransomware Cold", 5),

    # ── EMERGING THREATS (format 2 & 4 mix) ──────────────────────────────────
    ("How Quantum Computers Will Make All Current Encryption Useless", 4),
    ("Post-Quantum Cryptography: The Race to Secure the Internet Before Q-Day", 2),
    ("How AI Is Making Phishing So Convincing That Even Experts Are Fooled", 2),
    ("The Rise of Ransomware-as-a-Service: Anyone Can Be a Hacker Now", 2),
    ("How Hackers Are Targeting AI Models Themselves — Model Poisoning Explained", 4),
    ("Why 5G Networks Create New Attack Surfaces We're Not Prepared For", 2),
    ("How Cybercriminals Are Using Generative AI to Scale Attacks 100x", 2),
    ("The Coming Satellite Hacking Threat Nobody Is Talking About", 2),
    ("How AI-Generated Synthetic Media Will Make Insider Trading Unprovable", 2),
    ("The Rise of Living-off-the-Land Attacks That Use Your Own Tools Against You", 2),
    ("How Hackers Are Using Legitimate Cloud Services to Hide Their Attacks", 4),
    ("Why Industrial Control Systems Are the Next Big Ransomware Target", 2),
    ("How Hackers Are Exploiting GitHub Actions in Supply Chain Attacks", 4),
    ("The Threat of AI-Assisted OSINT for Targeted Spear Phishing", 2),
    ("How Deepfake Audio Is Being Used in Real-Time Phone Scams", 2),
    ("The Rise of API Attacks: Why Your App's Backend Is the Weakest Link", 2),
    ("How Smart Contract Vulnerabilities Are Draining Billions from DeFi", 4),
    ("Why Healthcare Is the Most Targeted Industry for Ransomware in 2025", 2),
    ("How AI Chatbots Can Be Weaponized to Spread Disinformation at Scale", 2),
    ("The Growing Threat of Cybersecurity Attacks on Space Infrastructure", 2),

    # ── HACKER CULTURE & HISTORY (format 1 & 4 mix) ──────────────────────────
    ("Kevin Mitnick: The Most Wanted Hacker in History — His Full Story", 1),
    ("Anonymous: The Decentralized Hacking Collective That Took on Governments", 1),
    ("Gary McKinnon: The Autistic Hacker Who Broke Into NASA Looking for UFOs", 1),
    ("Albert Gonzalez: How One Man Stole 170 Million Credit Cards", 1),
    ("The Morris Worm 1988: The Internet's First Cyberattack", 1),
    ("Kimsuky: North Korea's Cyber Espionage Group Targeting Nuclear Secrets", 1),
    ("APT41: China's Hacker Group That Blends Espionage With Financial Crime", 1),
    ("Fancy Bear: The Russian Hackers Behind the 2016 US Election Interference", 1),
    ("Scattered Spider: The Gen Z Hacking Gang That Breached MGM and Caesars", 1),
    ("The LockBit Takedown: How Interpol Dismantled the World's Top Ransomware Gang", 1),
    ("How the FBI Caught the Hacker Who Stole $4.5 Billion in Bitcoin", 1),
    ("The Silk Road Story: How Ross Ulbricht Built — and Lost — a $1B Dark Web Empire", 1),
    ("Operation Payback: Anonymous Attacks PayPal, Visa, and MasterCard", 1),
    ("Julian Assange: WikiLeaks, Surveillance, and a Decade-Long Legal Battle", 1),
    ("Edward Snowden: How One Man Exposed the NSA's Global Surveillance Program", 1),
    ("How the FBiOS Battle Between Apple and the FBI Changed Privacy Law Forever", 1),
    ("The Carbanak Gang: Eastern European Hackers Who Stole $1B from Banks", 1),
    ("How Elite Bug Bounty Hunters Make $1M a Year Finding Security Flaws", 4),
    ("What Happens Inside a Red Team Exercise at a Fortune 500 Company", 4),
    ("How DEF CON Became the World's Most Dangerous and Respected Hacker Conference", 4),

    # ── GOVERNMENT & GEOPOLITICS (format 1 & 2) ──────────────────────────────
    ("How the CIA's Vault 7 Hacking Arsenal Was Leaked by Its Own Employee", 1),
    ("China's Great Firewall: How 1.4 Billion People Are Surveilled Online", 4),
    ("Russia's Information Warfare Playbook — Exposed", 4),
    ("How North Korea Uses Crypto Hacking to Fund Its Nuclear Program", 4),
    ("Iran's Cyber Capabilities: From Shamoon to Targeting Saudi Arabia", 1),
    ("The Five Eyes Alliance: How 5 Countries Share Your Surveillance Data", 4),
    ("How CISA Fights Cyberattacks on US Critical Infrastructure", 4),
    ("The Vulnerability Equities Process: Why Governments Stockpile Zero-Days", 4),
    ("How the US Government Uses Cyber Operations as Foreign Policy Tools", 4),
    ("The Budapest Convention: The Only International Cybercrime Treaty That Exists", 4),
    ("How the EU's GDPR Changed Global Privacy Law — and Its Massive Failures", 4),
    ("Why the UN Can't Agree on Global Cybersecurity Norms", 4),
    ("How India's Aadhaar Biometric Database Exposed 1.2 Billion Citizens", 1),
    ("How Governments Are Building Social Credit Systems Using AI", 2),
    ("The NSA's PRISM Program: What We Know About Mass Surveillance Today", 4),

    # ── MOBILE & IOT SECURITY ─────────────────────────────────────────────────
    ("How Hackers Exploit Bluetooth to Access Nearby Phones Without Touching Them", 4),
    ("The NSO Group's iPhone Zero-Click Exploit: No Tap Required to Hack You", 1),
    ("How Smart Home Devices Are the Easiest Entry Point Into Your Network", 4),
    ("Why Your Baby Monitor Is Probably Accessible to Anyone on the Internet", 2),
    ("How Medical IoT Devices Are Being Hacked in Hospitals Right Now", 2),
    ("The Danger of Free Phone Charging Cables From Unknown Sources", 4),
    ("How Rogue Cell Towers (IMSI Catchers) Intercept Your Calls and Texts", 4),
    ("Why Your Smart Thermostat Knows More About You Than Your Doctor", 2),
    ("How Industrial IoT Devices Are Becoming Attack Vectors for Nation-States", 4),
    ("The Security Nightmare of 5 Billion Unpatched IoT Devices on the Internet", 2),

    # ── CRYPTOCURRENCY & FINANCIAL CRIME ──────────────────────────────────────
    ("How Crypto Exchanges Get Hacked — And Why Withdrawals Disappear", 4),
    ("How Romance Scammers Steal $1 Billion a Year Through Crypto Pig Butchering", 4),
    ("The NFT Scam Ecosystem: Rug Pulls, Wash Trading, and Fake Hype", 4),
    ("How DeFi Flash Loan Attacks Drain Hundreds of Millions in Seconds", 4),
    ("How Crypto Mixer Tornado Cash Was Sanctioned — and Why It Still Runs", 4),
    ("How Hackers Use Crypto to Launder Ransomware Payments Across Borders", 4),
    ("Why On-Chain Data Makes Crypto Less Anonymous Than Cash", 3),
    ("How Chainalysis Traces Stolen Crypto Across 100 Wallets", 4),
    ("The FTX Collapse: Was Sam Bankman-Fried a Fraudster or Just Incompetent?", 1),
    ("How North Korea's Lazarus Group Has Stolen $3B in Crypto Since 2017", 1),

    # ── AI SAFETY & ETHICS ────────────────────────────────────────────────────
    ("Why AI Alignment Is the Most Important Unsolved Problem in Computer Science", 2),
    ("How AI Systems Develop Emergent Behaviors Their Creators Didn't Program", 2),
    ("The Paperclip Maximizer: The Thought Experiment That Terrifies AI Researchers", 4),
    ("Why Anthropic and OpenAI Are Racing to Solve AI Safety Before It's Too Late", 2),
    ("How Bias in AI Training Data Creates Racist and Discriminatory Systems", 4),
    ("The Danger of AI Models That Learn to Deceive Their Operators", 2),
    ("How Regulatory Capture Could Make AI Safety Laws Meaningless", 2),
    ("Why Some of the World's Top AI Scientists Signed a Letter Calling for a Pause", 2),
    ("The Case for Open-Source AI — and Why It's Also the Case Against It", 3),
    ("How AI Is Already Being Used in Autonomous Weapons Systems", 2),
    ("The Real Reason Big Tech Is Scared of AI Regulation", 2),
    ("How Deepfakes Are Undermining Trust in Video Evidence in Courtrooms", 2),
    ("AI-Generated CSAM: The Darkest Consequence of Generative AI", 2),
    ("Why the EU AI Act Is Either the Future of Governance or a Disaster", 2),
    ("How China and the US Are Competing for AI Dominance — and What It Means for You", 2),

    # ── SOCIAL ENGINEERING & SCAMS ────────────────────────────────────────────
    ("The Full Anatomy of a Spear Phishing Attack — From Research to Click", 4),
    ("How Pretexting Lets Hackers Get Your Information by Simply Asking", 4),
    ("The Psychology of Why Smart People Fall for Obvious Scams", 4),
    ("How Romance Scammers Build Fake Relationships Over 6 Months to Steal Millions", 4),
    ("The IRS Phone Scam: How It Works and Why It Still Fools People", 4),
    ("How Grandparent Scams Target Elderly Victims Using AI Voice Cloning", 4),
    ("The Anatomy of a Business Email Compromise Attack That Costs $2.9B a Year", 4),
    ("How Scammers Impersonate Tech Support to Get Remote Access to Your Computer", 4),
    ("The Pig Butchering Scam Playbook: Crypto Fraud That's Stolen $75B", 4),
    ("How Deepfake Video Calls Are Being Used to Bypass Identity Verification", 2),
    ("How Social Engineers Used LinkedIn to Infiltrate Defense Contractors", 1),
    ("The Advance Fee Fraud Evolution: From Nigerian Prince to AI Impersonators", 4),
    ("How Quishing (QR Code Phishing) Bypasses Every Email Security Filter", 4),
    ("How Package Delivery Text Scams Are Stealing Banking Credentials at Scale", 4),
    ("The Anatomy of a Fake Job Offer That Installs Malware on Your Computer", 4),

    # ── ADDITIONAL INCIDENT BREAKDOWNS ────────────────────────────────────────
    ("The Google Project Zero Team: Elite Hackers Who Find Flaws Before the Bad Guys", 4),
    ("How Bug Bounty Programs Pay Hackers to Find Vulnerabilities Legally", 4),
    ("The Whistleblower Who Exposed Facebook's Internal Research on Teen Mental Health", 1),
    ("How the CIA Used a Fake Vaccination Program as Cover for Intelligence Operations", 1),
    ("The Juniper Networks Backdoor: Someone Hid a Secret in US Network Equipment", 1),
    ("The 2003 Northeast Blackout: How a Software Bug Cascaded Into Disaster", 1),
    ("How the Boeing 737 MAX Software Failure Killed 346 People", 1),
    ("The Knight Capital Algorithm Disaster: $440M Lost in 45 Minutes of Bad Code", 1),
    ("How an Amazon EC2 Misconfiguration Took Down the Internet for 8 Hours in 2017", 1),
    ("The Facebook Outage 2021: How a Single BGP Change Deleted Facebook From the Internet", 1),
    ("How a Faulty CrowdStrike Update Grounded Planes and Closed Hospitals Worldwide", 1),
    ("The Therac-25 Radiation Machine: How a Software Bug Killed 6 Cancer Patients", 1),
    ("How Tesla's Autopilot Has Been Tricked by Simple Adversarial Patches on Roads", 1),
    ("The SIM Swap That Stole $24M in Cryptocurrency From One Person in One Night", 1),
    ("How a Security Researcher Found a Backdoor in XZ Utils Before It Hit Production", 1),

    # ── ADDITIONAL FORMAT 5 LISTS ─────────────────────────────────────────────
    ("5 Chrome Extensions You Should Delete Right Now", 5),
    ("The 6 Biggest Cybersecurity Predictions for 2025 That Already Came True", 5),
    ("4 Ransomware Families That Are Targeting You Right Now", 5),
    ("7 Cybersecurity Certifications That Are Actually Worth It in 2025", 5),
    ("5 Open-Source Intelligence Tools That Are Terrifyingly Powerful", 5),
    ("The 3 Most Underrated Privacy Tools Nobody Is Talking About", 5),
    ("8 Things Hackers Can Learn About You From One Photo", 5),
    ("5 Biggest Cybersecurity Mistakes That Got CEOs Fired", 5),
    ("The 4 Most Common Ransomware Entry Points in Corporate Networks", 5),
    ("6 Questions to Ask Before Trusting Any Security Company With Your Data", 5),

    # ── ADDITIONAL FORMAT 3 MYTH BUSTERS ─────────────────────────────────────
    ("You Think Paying Ransomware Gets Your Files Back? Most Victims Get Nothing", 3),
    ("You Think Your Kids Are Safe Online Because of Parental Controls? Not Really", 3),
    ("You Think Cybersecurity Is Only for Big Companies? Your Startup Is the Target", 3),
    ("You Think AI Art Generators Are Just Creative Tools? Here's the Dark Side", 3),
    ("You Think End-to-End Encryption Means Nobody Can Read Your Messages? Almost", 3),
    ("You Think Hackers Are After You Personally? The Reality Is More Frightening", 3),
    ("You Think a Firewall Alone Protects Your Network? Modern Attackers Walk Right Through", 3),
    ("You Think Tor Makes You Completely Anonymous? Law Enforcement Disagrees", 3),
    ("You Think Encrypted Email Is Private? The Metadata Tells Everything", 3),
    ("You Think Your Smart Lock Is More Secure Than a Deadbolt? Think Again", 3),
    ("You Think Free Antivirus Is Enough? Here's What It Misses", 3),
    ("You Think Hackers Need to Trick You Into Clicking Something? Zero-Clicks Changed Everything", 3),
    ("You Think Cloud Storage Is Automatically Backed Up? Read the Terms", 3),
    ("You Think Using a Password Manager Is Risky? Not Using One Is Riskier", 3),
    ("You Think Your Old Deleted Social Media Posts Are Gone? They're Not", 3),
    ("You Think AI-Generated Text Is Always Detectable? Detectors Are Already Failing", 3),
    ("You Think Cybersecurity Is About Technical Skill? Social Engineering Wins Every Time", 3),
    ("You Think Disconnecting From the Internet Keeps You Safe? Air-Gap Attacks Are Real", 3),
    ("You Think Your Home Network Is Separate From Your Work Network? VPNs Blur That Line", 3),
    ("You Think Open-Source Software Is More Secure? The XZ Utils Backdoor Says Otherwise", 3),

    # ── MORE FORMAT 5 LISTS ───────────────────────────────────────────────────
    ("5 Countries Where the Government Can Demand Access to Your Device at the Border", 5),
    ("7 Cybersecurity Terms Everyone Gets Wrong", 5),
    ("The 4 Most Dangerous Hacking Techniques That Require Zero Technical Skill", 5),
    ("6 Red Flags That a Job Offer Is Actually a Malware Installation Scam", 5),
    ("5 Things to Check Before Plugging Any USB Device Into Your Computer", 5),
    ("The 3 Best Password Managers in 2025 — Ranked by Security", 5),
    ("8 Privacy-Respecting Alternatives to Big Tech Products", 5),
    ("5 Ways Nation-State Hackers Are Different From Criminal Hackers", 5),
    ("The 6 Most Valuable Things Hackers Steal — It's Not Always Money", 5),
    ("4 Zero-Day Vulnerabilities That Changed Cybersecurity History", 5),
    ("7 Smart Steps to Take After a Data Breach Notification Email", 5),
    ("5 AI Companies That Had Major Security or Privacy Incidents in 2024", 5),
    ("The 3 Most Dangerous Cyber Threats to Small Businesses in 2025", 5),
    ("6 Common Cybersecurity Interview Questions and Their Real Answers", 5),
    ("5 Reasons Two-Factor Authentication via Authenticator App Beats SMS", 5),
    ("The 4 Biggest Misconceptions About Cybersecurity Careers", 5),
    ("7 Signs Your Email Account Has Already Been Compromised", 5),
    ("5 Free Cybersecurity Tools That Professionals Actually Use", 5),
    ("The 3 Types of People Most Targeted by Hackers — Are You One of Them?", 5),
    ("6 Things That Happen to Your Data After a Company Sells It", 5),
    ("5 Websites That Reveal Terrifying Amounts of Info About You for Free", 5),
    ("The 4 Biggest Ransomware Mistakes Victims Make That Make Things Worse", 5),
    ("8 Cybersecurity Habits That Take Under 5 Minutes and Protect You for Years", 5),
    ("5 Ways AI Is Being Used to Improve Cybersecurity Defenses Right Now", 5),
    ("The 6 Most Common Attack Vectors for Corporate Network Breaches", 5),
    ("4 Times Bug Bounty Hunters Found Catastrophic Vulnerabilities in Major Platforms", 5),
    ("7 Pieces of Information You Should Never Post on Social Media", 5),
    ("5 Things Your Phone Knows About You That Your Doctor Doesn't", 5),
    ("The 3 Biggest Flaws in How Companies Handle Data Breach Notifications", 5),
    ("6 Security Headers Every Website Should Have — and Most Don't", 5),
    ("5 Industries That Are Completely Unprepared for Cyberattacks", 5),
    ("The 4 Stages of a Ransomware Attack — From First Click to Ransom Note", 5),
    ("7 Countries That Have the Weakest Cybersecurity Laws", 5),
    ("5 AI-Powered Scam Tactics That Are New in the Last 12 Months", 5),
    ("The 3 Most Successful Social Engineering Attacks on Government Systems", 5),

    # ── MORE FORMAT 6 NEWS REACT PLACEHOLDERS ─────────────────────────────────
    ("LIVE: New Malware Family Targeting Financial Institutions — News React", 6),
    ("LIVE: Critical Vulnerability in Widely Used Open-Source Library", 6),
    ("LIVE: AI Regulation Bill Introduced — Cybersecurity Implications", 6),
    ("LIVE: Major Cloud Provider Outage Tied to Security Incident", 6),
    ("LIVE: Hacking Group Claims Breach of Government Agency", 6),
    ("LIVE: New Deepfake Scam Campaign Targeting Executives", 6),
    ("LIVE: International Cybercrime Ring Dismantled by Europol", 6),
    ("LIVE: Zero-Day in Popular Software Used in Active Attacks", 6),
    ("LIVE: Data Broker Exposed — Millions of Records Available Online", 6),
    ("LIVE: AI Startup's Model Jailbroken to Produce Dangerous Content", 6),
    ("LIVE: Record Ransomware Payment Confirmed by Insurance Firm", 6),
    ("LIVE: Smart City Infrastructure Targeted by Hackers", 6),
    ("LIVE: Major Social Platform Admits Training AI on Private Messages", 6),
    ("LIVE: Cyberattack Disrupts Hospital Network Across Multiple States", 6),
    ("LIVE: New Spyware Tool Found Targeting Journalists and Activists", 6),
    ("LIVE: Election Infrastructure Security Report Released", 6),
    ("LIVE: Critical Infrastructure Attack — Details Emerging", 6),
    ("LIVE: AI Company Discloses Training Data Security Incident", 6),
    ("LIVE: International Sanctions Imposed on Ransomware Operators", 6),
    ("LIVE: New Privacy Law Passes — What It Means for Big Tech", 6),

    # ── MORE FORMAT 1 INCIDENT BREAKDOWNS ─────────────────────────────────────
    ("The Cognizant Maze Ransomware Attack: $70M Ransom for an IT Giant", 1),
    ("How Iranian Hackers Targeted Israeli Water Infrastructure in 2020", 1),
    ("The Garmin Ransomware Attack: WastedLocker Took Down GPS Services Worldwide", 1),
    ("The SolarWinds Hack: The Full 14-Month Timeline of the Most Sophisticated Attack", 1),
    ("The Bangladesh Swift Heist: $81M Stolen via Typo That Saved $850M More", 1),
    ("How Hackers Stole $600M From Poly Network — Then Had a Conversation With the Blockchain", 1),
    ("The Rackspace Email Server Breach: PLAY Ransomware Wiped Customer Data", 1),
    ("How Anonymous Took Down HBGary Federal in 3 Days Using SQL Injection", 1),
    ("The LifeLabs Breach: 15 Million Canadian Patient Records Held for Ransom", 1),
    ("The 3CX Supply Chain Attack: A Hacked App Infected Millions of Businesses", 1),
    ("The Flagstar Bank Breach: Hackers Stole Social Security Numbers of 1.5M Customers", 1),
    ("How Lazarus Group Stole $625M From Axie Infinity's Ronin Bridge", 1),
    ("The Ferrari Data Breach: Hackers Demanded Ransom — Ferrari Refused to Pay", 1),
    ("How a Single Spreadsheet Error Caused Knight Capital to Lose $440M", 1),
    ("The Kronos Payroll Hack: Ransomware Left Thousands of Workers Without Pay for Weeks", 1),

    # ── MORE FORMAT 4 HOW IT WORKS ────────────────────────────────────────────
    ("How OAuth2 Works — And How Attackers Exploit It", 4),
    ("How JWT Tokens Are Forged to Gain Unauthorized Access", 4),
    ("How BGP Hijacking Can Redirect Internet Traffic for an Entire Country", 4),
    ("How Cross-Site Scripting (XSS) Steals Your Session Without You Knowing", 4),
    ("How Subdomain Takeovers Let Hackers Host Phishing Pages on Legitimate Domains", 4),
    ("How Ransomware Operators Spend Months Inside a Network Before Encrypting", 4),
    ("How IDOR Vulnerabilities Expose Other Users' Private Data With a Simple URL Change", 4),
    ("How Packet Sniffing Works — And Why Unencrypted WiFi Is a Gift to Hackers", 4),
    ("How Typosquatting Tricks Developers Into Downloading Malicious Packages", 4),
    ("How Container Escape Attacks Break Out of Docker and Kubernetes Sandboxes", 4),
    ("How Kerberoasting Extracts Windows Domain Credentials Without Admin Rights", 4),
    ("How Pass-the-Hash Attacks Let Hackers Authenticate Without Knowing Your Password", 4),
    ("How Path Traversal Lets Attackers Read Any File on a Web Server", 4),
    ("How SSRF Tricks Servers Into Making Requests They Shouldn't", 4),
    ("How Polymorphic Malware Rewrites Itself to Evade Every Signature-Based Scanner", 4),

    # ── ADDITIONAL FORMAT 2 AI REVEALS ───────────────────────────────────────
    ("This AI Can Predict Which Employees Will Quit — Before They Know Themselves", 2),
    ("An AI Beat Human Poker Champions by Bluffing — Then Lied About How It Won", 2),
    ("This AI System Learned to Manipulate Humans in Negotiations Without Being Programmed To", 2),
    ("GPT-4 Hired a Human to Solve a CAPTCHA by Pretending to Be Visually Impaired", 2),
    ("This AI Discovered a Novel Antibiotic That Kills Drug-Resistant Bacteria", 2),
    ("How AI Systems Are Now Patching Their Own Vulnerabilities Without Human Input", 2),
    ("An AI Model Achieved Superhuman Performance on Cybersecurity CTF Challenges", 2),
    ("This AI Can Identify Your Political Views From Your Face With 72% Accuracy", 2),
    ("How Large Language Models Are Being Used to Automate APT Reconnaissance", 2),
    ("The AI System That Can Break CAPTCHAs Designed Specifically to Defeat AI", 2),

    # ── FINAL BATCH TO REACH 500 ──────────────────────────────────────────────
    ("How Hackers Use Google Dorks to Find Exposed Databases With a Single Search", 4),
    ("The Most Dangerous Piece of Code Ever Written — The Morris Worm Explained", 1),
    ("5 Times Ethical Hackers Saved Companies From Catastrophic Breaches", 5),
    ("You Think Deleting Your Google Search History Removes It? Here's the Truth", 3),
    ("LIVE: Massive Breach at a Major Retailer — Customer Payment Data Exposed", 6),
    ("How Shoulder Surfing Steals Your PIN — And How to Stop It", 4),
    ("The 4 Biggest Mistakes That Get Security Professionals Fired", 5),
    ("How Hackers Use Legitimate Google Ads to Deliver Malware to Searchers", 4),
    ("LIVE: AI Regulation Framework Announced — What Changes for Tech Companies", 6),
]
# fmt: on


def build_topics() -> list[dict]:
    """Build the full list of topic dicts from raw topic tuples."""
    return [
        {
            "id": idx + 1,
            "topic": topic,
            "format": fmt,
            "used": False,
            "date_used": None,
        }
        for idx, (topic, fmt) in enumerate(RAW_TOPICS)
    ]


def main() -> None:
    """Generate topics.json and write it to the project root."""
    topics = build_topics()
    out_path = Path(__file__).parent / "topics.json"
    out_path.write_text(json.dumps(topics, indent=2, ensure_ascii=False))

    # Stats breakdown
    from collections import Counter
    fmt_counts = Counter(t["format"] for t in topics)
    print(f"✅  Written {len(topics)} topics to {out_path}")
    print(f"\n📊  Format breakdown:")
    labels = {
        1: "Incident Breakdown",
        2: "AI Reveal",
        3: "Myth Buster",
        4: "How It Works",
        5: "List / Ranking",
        6: "News React",
    }
    for fmt_id in sorted(fmt_counts):
        print(f"   Format {fmt_id} — {labels[fmt_id]}: {fmt_counts[fmt_id]}")


if __name__ == "__main__":
    main()
