"""
scene_director.py — Generates custom Remotion TSX scene components via Claude Haiku.

For each SceneDescription, sends a tailored prompt to Claude Haiku that asks it to
write a self-contained React/TSX component with animations specific to the scene's
content: counters that tick to real numbers, SVG diagrams, typing/terminal effects,
spawning icon swarms, radar sweeps, progress bars, etc.

All generated components are combined into one file:
    remotion-video/src/scenes/generated/AllGeneratedScenes.tsx

CipherPulseComposition.tsx looks up each scene.id in GENERATED_SCENE_REGISTRY first,
then falls back to the static template components (CyberGrid, DataStream, etc.) if
the ID is absent (generation failed or tsc validation rejected the file).

Public API:
    generate_custom_scenes(scenes, script_text, title, api_key) -> None
"""

from __future__ import annotations

import logging
import os
import re
import subprocess
from pathlib import Path
from typing import Optional

import anthropic
from dotenv import load_dotenv

load_dotenv()

log = logging.getLogger(__name__)

# ── Paths ─────────────────────────────────────────────────────────────────────
REMOTION_DIR   = Path(__file__).parent.parent / "remotion-video"
GENERATED_DIR  = REMOTION_DIR / "src" / "scenes" / "generated"
GENERATED_FILE = GENERATED_DIR / "AllGeneratedScenes.tsx"

# ── Constants ─────────────────────────────────────────────────────────────────
MODEL      = "claude-haiku-4-5-20251001"
MAX_TOKENS = 3500   # 2048 was too tight → components truncated mid-expression
FPS        = 30

_STUB_CONTENT = """\
// AUTO-GENERATED by CipherPulse scene_director.py
// Stub: scene generation failed or TypeScript validation rejected output.
// All scenes fall back to static CipherPulse templates.

import React from "react";
import { SceneData } from "../../types";

export const GENERATED_SCENE_REGISTRY: Record<string, React.FC<{ scene: SceneData }>> = {};
"""

# ── Known Haiku output errors to auto-correct before combining ────────────────
# String replacements (case-sensitive)
_TYPO_FIXES: list[tuple[str, str]] = [
    ("extraplateRight",  "extrapolateRight"),
    ("extraplateLeft",   "extrapolateLeft"),
    ("extrapolateright", "extrapolateRight"),
    ("extrapolateleft",  "extrapolateLeft"),
]

# Regex replacements applied after string fixes
_REGEX_FIXES: list[tuple[str, str]] = [
    # spring() called with 3 positional args instead of one options object
    # spring(frameExpr, fps, {config}) → spring({ frame: frameExpr, fps, config: {config} })
    (
        r"\bspring\(\s*([^,{}\n]+?),\s*fps\s*,\s*(\{[^{}]*\})\)",
        r"spring({ frame: \1, fps, config: \2 })",
    ),
    (
        r"\bspring\(\s*([^,{}\n]+?),\s*fps\s*,\s*([A-Za-z_]\w*)\s*\)",
        r"spring({ frame: \1, fps, config: \2 })",
    ),
    # Fake CSS border-side opacity properties — not valid in React inline styles
    # Remove them entirely; the border will render at full opacity instead
    (r"\bborder(?:Top|Bottom|Left|Right)Opacity\s*:[^,}\n]+,?\s*", ""),
    # Other invented CSS properties Haiku occasionally produces
    (r"\bbackgroundOpacity\s*:[^,}\n]+,?\s*", ""),
    (r"\btextShadowOpacity\s*:[^,}\n]+,?\s*", ""),
    (r"\bboxShadowOpacity\s*:[^,}\n]+,?\s*", ""),
]

# ── System prompt ──────────────────────────────────────────────────────────────
_SYSTEM = """\
You are a Remotion React/TypeScript expert writing animated video scenes for CipherPulse,
a dark cybersecurity news short-form video channel.

Write ONE self-contained TypeScript React component that visually illustrates the given
scene concept with rich, SPECIFIC animations tailored to what the narration describes.

━━━ ALLOWED IMPORTS (single-line only, exactly these) ━━━━━━━━━━━━━━━━━━━━━━━━━
import React from "react";
import { useCurrentFrame, useVideoConfig, interpolate, spring, Easing, AbsoluteFill } from "remotion";
import { SceneData } from "../../types";

DO NOT use: useState, useEffect, useRef, or any React hook other than Remotion's.
DO NOT use: staticFile, Audio, Img, or any asset loading.
DO NOT use: Math.random() — it re-runs every frame and causes flickering.
  Instead, define randomised positions as a const array BEFORE the return statement:
    const POS = [{ x: 200, y: 400 }, { x: 700, y: 900 }, ...];

━━━ CANVAS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1080 × 1920 px | 30 fps | portrait 9:16
Usable width:  60px margin each side → 960px of content width
Usable height: y=150 to y=1750 (1600px of content height)

━━━ FRAME ZONES — place elements strictly within these bands ━━━━━━━━━━━━━━━━━━
  TOP ZONE    y=150  – y=500   (350px) — title, keyword, counter number
  MIDDLE ZONE y=500  – y=1200  (700px) — main visual: icons, diagrams, bars, SVG
  BOTTOM ZONE y=1200 – y=1750  (550px) — sub-labels, progress bars, caption

  CAPTION is ALWAYS in the BOTTOM ZONE at top: 1350px (see below).
  Elements in one zone must NOT overlap into another zone.
  Leave at least 40px gap between any two elements.

━━━ SIZING — EVERYTHING MUST BE LARGE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This is a phone screen viewed while scrolling — every element must hit immediately.

  Minimum icon / emoji font size:     120px
  Minimum shape / circle diameter:    200px  (timer rings ≥ 300px)
  Counter numbers:                    at least 140px font size
  Sub-labels under counters:          at least 36px font size
  Progress bar height:                at least 20px
  Terminal / code text:               at least 40px font size

Visual content must fill at least 60% of the 1080×1920 frame. The MIDDLE ZONE
(700px tall, 960px wide) should be densely filled — no large empty black voids.

━━━ OPENING FRAME — no empty starts ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Frame 0 must show visible animated content. Do NOT wait until frame 10 or 20 to
begin rendering. Background glows, scan lines, grid overlays, or partial elements
must be present from frame 0 so the screen is never blank.
  - Use interpolate(frame, [0, 20], ...) not [20, 40] for the first element
  - A subtle pulse or glow starting at frame 0 is always sufficient

━━━ CAPTION — fixed position, every scene ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Caption text (scene.caption) MUST be rendered with EXACTLY this style:
  position: "absolute"
  top: 1350
  left: 60
  right: 60
  textAlign: "center"
  color: "#E8E6E3"
  fontSize: 52
  fontWeight: 900
  lineHeight: 1.25
  textShadow: "0 2px 12px rgba(0,0,0,0.9)"
  margin: 0

Never change top: 1350. Never use bottom: instead of top:. Never move the caption.

━━━ LAYOUT — fill the frame, no clustering ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  - Distribute elements across the full 960px usable width
  - For icon grids: use left values like 60, 280, 500, 720, 940 (5 columns)
    or 60, 390, 720 (3 columns) — never cluster everything in the centre
  - Span at least 800px of vertical height with your content
  - No two elements should have overlapping bounding boxes (≥40px gap always)

━━━ BRAND COLORS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#060609 — background (always dark)
#00F2EA — cyan (tech / data / AI)
#FF3B3B — red (threat / breach / danger)
#00BCD4 — teal (network / scan)
#E8E6E3 — off-white (body text)

━━━ COMPONENT SIGNATURE (N = provided scene index) ━━━━━━━━━━━━━━━━━━━━━━━━━━━
export const GeneratedSceneN: React.FC<{ scene: SceneData }> = ({ scene }) => {
  const frame = useCurrentFrame();
  const { fps, width, height } = useVideoConfig();
  const totalFrames = Math.round(scene.duration_seconds * fps);
  const accent = scene.accent_color ?? "#00F2EA";
  // ...
  return (
    <AbsoluteFill style={{ background: "#060609", overflow: "hidden", fontFamily: "monospace" }}>
      {/* TOP ZONE: title or counter (y=150-500) */}
      {/* MIDDLE ZONE: main visual (y=500-1200) */}
      {/* BOTTOM ZONE: caption at top:1350 (y=1200-1750) */}
    </AbsoluteFill>
  );
};

━━━ ANIMATION REQUIREMENTS (ALL must be met) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Frame 0 is never blank — at least a background glow or grid must appear
2. Nothing static for more than 15 consecutive frames (0.5 s)
3. Elements animate IN — no instant full-opacity pop (use fade or scale)
4. Stagger element start frames: offset each by 8–20 frames
5. scene.caption at top:1350, fontSize:52 — always present from ~frame 20
6. At least 3 distinct animated elements in the MIDDLE ZONE
7. At least one spring() for a satisfying bounce on the key reveal

━━━ ANIMATION RECIPES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Counter (ticks to a specific number, 140px minimum):
const count = Math.floor(
  interpolate(frame, [0, totalFrames - 10], [0, 75000],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" })
);
// <div style={{ fontSize: 160, fontWeight: 900, color: accent }}>{count.toLocaleString()}</div>

// Progress bar (at least 20px tall):
const pct = interpolate(frame, [0, totalFrames - 10], [0, 100],
  { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
// <div style={{ width: `${pct}%`, height: 20, background: accent }} />

// SVG draw-in:
const DASH = 800;
const dashOffset = interpolate(frame, [0, 40], [DASH, 0],
  { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
// <path strokeDasharray={String(DASH)} strokeDashoffset={dashOffset} strokeWidth={6} />

// Typing / terminal (40px min font):
const cmd = "$ exploit --target=192.168.1.1";
const shown = cmd.slice(0, Math.floor(
  interpolate(frame, [0, 50], [0, cmd.length],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" })
));
// <div style={{ fontSize: 42 }}>{shown}{frame % 20 < 10 ? "█" : " "}</div>

// Spring pop-in:
const sc = spring({ frame: frame - 5, fps, config: { damping: 12, stiffness: 180 } });
// style={{ transform: `scale(${sc})` }}

// Glow pulse (start at frame 0):
const glow = 0.4 + 0.6 * Math.sin(frame * 0.15);

// Spawn items with stagger:
const visibleCount = Math.floor(
  interpolate(frame, [0, totalFrames / 2], [0, ITEMS.length],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" })
);

// Fade in with early start:
const opacity = interpolate(frame, [0, 15], [0, 1],
  { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

━━━ COMPLETE WORKING EXAMPLE (follow this layout and sizing) ━━━━━━━━━━━━━━━━━━

import React from "react";
import { useCurrentFrame, useVideoConfig, interpolate, spring, Easing, AbsoluteFill } from "remotion";
import { SceneData } from "../../types";

export const GeneratedSceneExample: React.FC<{ scene: SceneData }> = ({ scene }) => {
  const frame = useCurrentFrame();
  const { fps, width, height } = useVideoConfig();
  const totalFrames = Math.round(scene.duration_seconds * fps);
  const accent = scene.accent_color ?? "#00F2EA";

  // Background glow — visible from frame 0
  const bgGlow = 0.3 + 0.2 * Math.sin(frame * 0.1);

  // Counter 0 → 75,000 starting at frame 0
  const progress = spring({ frame: frame - 5, fps, config: { damping: 20, stiffness: 60 } });
  const count = Math.floor(progress * 75000);
  const countGlow = count >= 74000 ? 0.7 + 0.3 * Math.sin(frame * 0.3) : 0.5;

  // 6 large ID card icons — spread across MIDDLE ZONE in 3 columns × 2 rows
  // Each icon is 140px so rows are at y=560 and y=840 (200px apart — no overlap)
  const ICONS = ["💳", "👤", "🪪", "📧", "🔑", "🛡️"];
  const POS = [
    { x: 100, y: 560 }, { x: 440, y: 560 }, { x: 780, y: 560 },
    { x: 100, y: 840 }, { x: 440, y: 840 }, { x: 780, y: 840 },
  ];
  const visibleIcons = Math.floor(
    interpolate(frame, [5, 40], [0, ICONS.length],
      { extrapolateLeft: "clamp", extrapolateRight: "clamp" })
  );

  // Progress bar in BOTTOM ZONE (y≈1260, well above caption at 1350)
  const pct = interpolate(frame, [0, totalFrames - 10], [0, 100],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  // Caption fade from frame 0
  const captionOpacity = interpolate(frame, [0, 20], [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  return (
    <AbsoluteFill style={{ background: "#060609", overflow: "hidden", fontFamily: "monospace" }}>
      {/* Background radial glow — frame 0 visible */}
      <div style={{ position: "absolute", top: 400, left: 140, width: 800, height: 800,
        borderRadius: "50%", background: `radial-gradient(circle, ${accent}18 0%, transparent 70%)`,
        opacity: bgGlow }} />

      {/* TOP ZONE: large counter (y≈220) */}
      <div style={{ position: "absolute", top: 200, left: 0, right: 0, textAlign: "center" }}>
        <div style={{ fontSize: 160, fontWeight: 900, color: accent,
          textShadow: `0 0 60px ${accent}`, opacity: countGlow, lineHeight: 1 }}>
          {count.toLocaleString()}
        </div>
        <div style={{ fontSize: 40, color: "#E8E6E3", marginTop: 12, letterSpacing: 6 }}>
          FAKE IDENTITIES
        </div>
      </div>

      {/* MIDDLE ZONE: large icon grid (y=560–980) */}
      {POS.slice(0, visibleIcons).map((pos, i) => {
        const sc = spring({ frame: frame - i * 6, fps, config: { damping: 10, stiffness: 200 } });
        return (
          <div key={i} style={{ position: "absolute", left: pos.x, top: pos.y,
            fontSize: 140, transform: `scale(${sc})`, opacity: 0.85, lineHeight: 1 }}>
            {ICONS[i]}
          </div>
        );
      })}

      {/* BOTTOM ZONE: progress bar at y=1260 (90px above caption) */}
      <div style={{ position: "absolute", top: 1260, left: 60, right: 60,
        height: 20, background: "#222", borderRadius: 10 }}>
        <div style={{ width: `${pct}%`, height: "100%", background: accent,
          borderRadius: 10, boxShadow: `0 0 12px ${accent}` }} />
      </div>

      {/* CAPTION — fixed at top:1350, never changes */}
      <div style={{ position: "absolute", top: 1350, left: 60, right: 60,
        textAlign: "center", opacity: captionOpacity }}>
        <p style={{ color: "#E8E6E3", fontSize: 52, fontWeight: 900,
          lineHeight: 1.25, textShadow: "0 2px 12px rgba(0,0,0,0.9)", margin: 0 }}>
          {scene.caption}
        </p>
      </div>
    </AbsoluteFill>
  );
};

━━━ SVG NOTE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
In JSX/TSX, SVG attributes are camelCase:
  strokeDasharray, strokeDashoffset, strokeWidth, fillOpacity, strokeLinecap

━━━ HARD RULES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- TypeScript strict — no `any` type
- All data (labels, positions, colours) as const arrays BEFORE the return
- Root element MUST use background: "#060609"
- Caption MUST be at top:1350, fontSize:52, textShadow as shown — no exceptions
- Minimum icon size 120px, minimum counter font 140px, minimum bar height 20px
- Frame 0 must not be blank — start a glow or grid from frame 0
- Keep component under 110 lines of code
- Always close every JSX element you open — including </AbsoluteFill>
- Output ONLY the TypeScript code — no markdown fences, no prose
- Keep all text and visual elements within x=60 to x=820 to avoid YouTube's right-side UI buttons.
- No content above y=220 to avoid YouTube's header.
- All text must have 100px right margin. If text is too long, reduce font size or wrap — never let text go off screen.
- CRITICAL LAYOUT RULE FOR SIDE-BY-SIDE / COMPARISON SCENES: When a scene has two columns or two side-by-side elements (e.g. comparison cards, before/after, left vs right), the total layout must fit within x=60 to x=1020. Each column should be max 440px wide with a 40px gap between them. Left column: x=60 to x=500. Right column: x=540 to x=980. All text inside cards must word-wrap within the card bounds — never overflow past x=980. This prevents right-edge clipping on 1080px canvas.
- CRITICAL Z-LAYER / OVERLAP RULE: Emoji icons, images, and decorative visual elements must NEVER overlap text labels, headings, or caption text. Enforce strict vertical zones — the canvas is divided into 3 non-overlapping bands:
  TOP ZONE (y=80 to y=350): Large heading text (e.g. 'BREACH', 'CRITICAL', stat counters like '30M')
  MIDDLE ZONE (y=350 to y=1350): Icons, emojis, images, diagrams, progress bars, and decorative elements. All icons/emojis must be contained within this zone and must not extend above into the heading or below into the caption area.
  BOTTOM ZONE (y=1350 to y=1750): Caption/subtitle text and status labels (e.g. 'DATA LOSS', 'BREACH #1 + #2'). No icons or images in this zone.
  Never stack an emoji on top of text. If an icon grid would extend into the top or bottom text zones, shrink the icons or reduce the count to fit within the middle zone.
- EMOJI AND ICON LAYOUT RULES: When placing multiple emojis or icons in a scene, they must be arranged in a clean grid or structured layout — never scattered randomly or piled on top of each other. Use a maximum of 4-6 icons per scene. Arrange them in a grid pattern (e.g. 2x2 or 3x2) with at least 120px spacing between each icon. Each icon should be the same size (max 80px). Icons must stay within x=60 to x=980 and y=350 to y=1100. Never let icons overlap each other or overlap any text element.
- Caption/subtitle text at the bottom must use font-size 32px maximum, never larger.
"""


# ── Public API ─────────────────────────────────────────────────────────────────

def generate_custom_scenes(
    scenes: list[dict],
    script_text: str,
    title: str,
    api_key: Optional[str] = None,
) -> None:
    """Generate custom Remotion TSX components for each scene.

    Writes remotion-video/src/scenes/generated/AllGeneratedScenes.tsx which
    exports GENERATED_SCENE_REGISTRY — a map of scene.id → React component.

    CipherPulseComposition checks the registry first; if a scene ID is absent
    (generation failed or tsc rejected the file) it falls back to the matching
    static template (CyberGrid, DataStream, etc.).

    Args:
        scenes:      List of scene dicts — id, type, caption, duration_seconds,
                     accent_color, keyword.
        script_text: Full voiceover script for narrative context.
        title:       Video title.
        api_key:     ANTHROPIC_API_KEY override (defaults to env var).
    """
    resolved_key = api_key or os.getenv("ANTHROPIC_API_KEY")
    if not resolved_key:
        log.warning("[scene_director] ANTHROPIC_API_KEY not set — writing stub (template fallbacks)")
        _write_stub()
        return

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    client = anthropic.Anthropic(api_key=resolved_key)

    generated: list[tuple[int, str, str]] = []   # (index, scene_id, tsx_body)

    for i, scene in enumerate(scenes):
        scene_id = scene.get("id", f"scene-{i}")
        caption  = scene.get("caption", "")
        log.info("[scene_director] Scene %d/%d → %r", i + 1, len(scenes), caption[:60])
        try:
            tsx = _generate_component(client, scene, i, script_text, title)
            valid, reason = _sanity_check(tsx, i)
            if not valid:
                log.warning("[scene_director] Scene %d sanity check failed (%s) — template fallback", i, reason)
            else:
                generated.append((i, scene_id, tsx))
        except Exception as exc:
            log.warning("[scene_director] Scene %d generation failed (%s) — template fallback", i, exc)

    if not generated:
        log.warning("[scene_director] All scenes failed — writing stub")
        _write_stub()
        return

    _write_combined_file(generated, scenes)

    # Validate with tsc, removing individual failing scenes and retrying rather
    # than falling back to the stub for the entire video.
    log.info("[scene_director] Running tsc validation (up to 3 passes)…")
    valid = _validate_and_filter(generated, scenes)

    if not valid:
        log.warning("[scene_director] No valid custom scenes after tsc — writing stub")
        _write_stub()
        return

    if len(valid) < len(generated):
        removed = len(generated) - len(valid)
        log.info(
            "[scene_director] ✅ tsc passed after removing %d scene(s) — %d custom scene(s) active",
            removed, len(valid),
        )
    else:
        log.info("[scene_director] ✅ tsc passed — %d custom scene(s) active", len(valid))

    _log_example(valid[0])


# ── Internal helpers ───────────────────────────────────────────────────────────

def _generate_component(
    client: anthropic.Anthropic,
    scene: dict,
    index: int,
    script_text: str,
    title: str,
) -> str:
    """Call Haiku and return the raw TSX component code for one scene."""
    duration     = float(scene.get("duration_seconds", 5))
    total_frames = round(duration * FPS)
    caption      = scene.get("caption", "")
    scene_type   = scene.get("type", "CyberGrid")
    accent       = scene.get("accent_color", "#00F2EA")
    keyword      = scene.get("keyword", "")
    script_snip  = script_text[:380].strip()

    kw_line = f'Keyword to feature as large dramatic text: "{keyword}"' if keyword else ""

    user_msg = f"""SCENE REQUEST

Scene index:     {index}
Export name:     GeneratedScene{index}
Caption (exact text that must appear on screen): "{caption}"
{kw_line}
Scene type hint: {scene_type}
Accent color:    {accent}
Duration:        {duration:.1f}s = {total_frames} frames at 30 fps

Voiceover context:
"{script_snip}..."

Video title: "{title}"

Animate what "{caption}" means visually. Choose the approach that best fits:
  - Number in caption → counter ticking up with spring, glow when it hits the target
  - Hack/breach/attack → broken lock SVG drawing in, red scan line, alert corner brackets
  - AI/generate/code → terminal typing effect with simulated code output
  - Speed/time → countdown ring + progress bar
  - Scale/volume → icons spawning and spreading across the canvas with stagger
  - Process/flow → flow diagram: circles connected by animated SVG paths
  - Comparison → two columns sliding in from left/right

Write GeneratedScene{index}. Output only TypeScript code."""

    response = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system=_SYSTEM,
        messages=[{"role": "user", "content": user_msg}],
    )
    raw = response.content[0].text.strip()

    # Strip accidental markdown fences
    raw = re.sub(r"^```(?:typescript|tsx|ts)?\s*\n?", "", raw)
    raw = re.sub(r"\n?```\s*$",                         "", raw)
    raw = raw.strip()

    # Auto-correct known Haiku string typos
    for wrong, correct in _TYPO_FIXES:
        raw = raw.replace(wrong, correct)

    # Auto-correct known Haiku regex patterns
    for pattern, replacement in _REGEX_FIXES:
        raw = re.sub(pattern, replacement, raw)

    if f"GeneratedScene{index}" not in raw:
        raise ValueError(f"Generated code does not export GeneratedScene{index}")

    return raw


def _sanity_check(tsx: str, index: int) -> tuple[bool, str]:
    """Quick pre-tsc check: verify the component is complete and structurally sound.

    Catches the most common Haiku failure mode: token-limit truncation that leaves
    an AbsoluteFill unclosed or the component body incomplete.
    """
    name = f"GeneratedScene{index}"
    if f"export const {name}" not in tsx:
        return False, f"missing export const {name}"
    if "<AbsoluteFill" not in tsx:
        return False, "no AbsoluteFill element"
    if "</AbsoluteFill>" not in tsx:
        return False, "AbsoluteFill never closed (likely truncated by token limit)"
    stripped = tsx.rstrip()
    if not stripped.endswith("};"):
        tail = stripped[-40:].replace("\n", "↵")
        return False, f"component doesn't end with '}}' — likely truncated (tail: {tail!r})"
    return True, ""


def _strip_imports(tsx: str) -> str:
    """Strip all import declarations (handles single-line and multi-line forms).

    Strategy: find the line index of the LAST import statement end, then return
    everything after it.  This correctly handles both:
      import React from "react";          ← single-line
      import {                            ← multi-line
        useCurrentFrame,
        ...
      } from "remotion";
    """
    lines = tsx.splitlines()
    last_import_end = -1
    in_import = False

    for i, line in enumerate(lines):
        stripped = line.strip()
        if in_import:
            # End of a multi-line import block: `} from "...";` or just `};`
            if stripped.startswith("}") and ("from" in stripped or stripped == "};"):
                last_import_end = i
                in_import = False
            continue
        if stripped.startswith("import "):
            # Multi-line import if `{` appears without a matching `}`
            if "{" in stripped and "}" not in stripped:
                in_import = True
            else:
                last_import_end = i

    result = lines[last_import_end + 1:]
    while result and not result[0].strip():
        result.pop(0)
    return "\n".join(result)


def _write_combined_file(
    generated: list[tuple[int, str, str]],
    all_scenes: list[dict],
) -> None:
    """Combine all validated component bodies into AllGeneratedScenes.tsx."""
    caption_for: dict[str, str] = {
        s.get("id", f"scene-{i}"): s.get("caption", "")
        for i, s in enumerate(all_scenes)
    }

    lines: list[str] = [
        "// AUTO-GENERATED by CipherPulse scene_director.py — do not edit manually",
        "// Regenerated on every pipeline run. Each component is unique to this video.",
        "",
        'import React from "react";',
        'import { useCurrentFrame, useVideoConfig, interpolate, spring, Easing, AbsoluteFill } from "remotion";',
        'import { SceneData } from "../../types";',
        "",
    ]

    for idx, scene_id, tsx in generated:
        caption = caption_for.get(scene_id, "")
        sep = "─" * max(0, 64 - len(caption))
        lines.append(f"// ── Scene {idx}: {caption[:64]} {sep}")
        lines.append("")
        lines.append(_strip_imports(tsx))
        lines.append("")

    lines += [
        "// ── Generated Scene Registry ─────────────────────────────────────────────────────",
        "export const GENERATED_SCENE_REGISTRY: Record<string, React.FC<{ scene: SceneData }>> = {",
    ]
    for idx, scene_id, _ in generated:
        lines.append(f'  "{scene_id}": GeneratedScene{idx},')
    lines += ["};", ""]

    content = "\n".join(lines)
    GENERATED_FILE.write_text(content, encoding="utf-8")
    log.info(
        "[scene_director] Written %s (%d lines, %d custom scene(s))",
        GENERATED_FILE.name, content.count("\n"), len(generated),
    )


def _write_stub() -> None:
    """Write empty registry so CipherPulseComposition compiles with template fallbacks."""
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_FILE.write_text(_STUB_CONTENT, encoding="utf-8")
    log.info("[scene_director] Stub written to %s", GENERATED_FILE)


def _validate_and_filter(
    generated: list[tuple[int, str, str]],
    all_scenes: list[dict],
) -> list[tuple[int, str, str]]:
    """Validate with tsc, surgically removing any scene that has errors, and retrying.

    Up to 3 passes: each pass identifies which scene(s) contain tsc errors by
    mapping error line numbers back to scene positions in the combined file.
    Those scenes are dropped and the file is rewritten without them.

    Returns the filtered list of clean (index, scene_id, tsx) tuples, or an
    empty list if nothing can be salvaged.
    """
    valid = list(generated)

    for attempt in range(3):
        if not valid:
            return []

        if attempt > 0:
            _write_combined_file(valid, all_scenes)

        errors = _tsc_errors_in_generated_file()
        if not errors:
            return valid  # ✅ clean

        # Map error line numbers back to scene indices
        failing = _failing_scene_indices(valid, errors)

        if not failing:
            # Errors exist but not attributable to any generated scene —
            # likely pre-existing project issues; proceed with all scenes.
            log.warning(
                "[scene_director] tsc errors not attributable to generated scenes — proceeding"
            )
            return valid

        log.warning(
            "[scene_director] Pass %d: dropping %d scene(s) with tsc errors (indices: %s)",
            attempt + 1, len(failing), sorted(failing),
        )
        valid = [(i, sid, tsx) for i, sid, tsx in valid if i not in failing]

    # After 3 passes return whatever is left (may be empty)
    return valid


def _tsc_errors_in_generated_file() -> list[tuple[int, str]]:
    """Run tsc --noEmit and return (line_number, message) for errors in our generated file."""
    try:
        result = subprocess.run(
            ["npx", "--yes", "tsc", "--noEmit"],
            cwd=str(REMOTION_DIR),
            capture_output=True,
            text=True,
            timeout=60,
        )
    except subprocess.TimeoutExpired:
        log.warning("[scene_director] tsc timed out — assuming valid")
        return []
    except FileNotFoundError:
        log.warning("[scene_director] tsc/npx not found — skipping validation")
        return []

    if result.returncode == 0:
        return []

    errors: list[tuple[int, str]] = []
    for line in (result.stdout + result.stderr).splitlines():
        if "AllGeneratedScenes" in line and "error TS" in line:
            m = re.search(r"\((\d+),\d+\)", line)
            if m:
                errors.append((int(m.group(1)), line))
                log.warning("[tsc] %s", line)

    return errors


def _failing_scene_indices(
    generated: list[tuple[int, str, str]],
    errors: list[tuple[int, str]],
) -> set[int]:
    """Map tsc error line numbers back to scene indices in AllGeneratedScenes.tsx.

    Reconstructs the line layout of the combined file to determine which scene
    component each error line falls within.
    """
    # File header is always 7 lines (2 comments + blank + 3 imports + blank)
    HEADER_LINES = 7

    # Build (start_line, end_line, scene_idx) for each scene
    ranges: list[tuple[int, int, int]] = []
    current = HEADER_LINES + 1   # 1-indexed line counter

    for scene_idx, _scene_id, tsx in generated:
        start = current
        body        = _strip_imports(tsx)
        body_lines  = len(body.splitlines())
        # separator comment  (+1)
        # blank line         (+1)
        # body lines         (+body_lines)
        # trailing blank     (+1)
        end     = start + 1 + 1 + body_lines + 1
        ranges.append((start, end, scene_idx))
        current = end + 1

    failing: set[int] = set()
    for err_line, _ in errors:
        for start, end, scene_idx in ranges:
            if start <= err_line <= end:
                failing.add(scene_idx)
                break

    return failing


def _log_example(entry: tuple[int, str, str]) -> None:
    """Log the first generated scene component so the user can inspect it."""
    idx, scene_id, tsx = entry
    lines = tsx.splitlines()
    bar = "─" * 72
    log.info("[scene_director] %s", bar)
    log.info("[scene_director] EXAMPLE — GeneratedScene%d (id: %s)", idx, scene_id)
    log.info("[scene_director] %s", bar)
    for line in lines:
        log.info("[scene_director]   %s", line)
    log.info("[scene_director] %s (%d lines total)", bar, len(lines))
